# Generated by Django 5.1.2 on 2024-10-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('predicted_rating', models.IntegerField()),
                ('sentiment', models.CharField(max_length=10)),
            ],
        ),
    ]
